version: '2'

services:
  simpleapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=sql.data;Database=SimplePersistence;User Id=sa;Password=Pass@word
    ports:
      - "5000:80"
  simpledata:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Pass@word
    ports:
      - "1433:1433"
